name: flutter_chrome
description: A Flutter package to streamline Chrome extension development with intuitive setup and build tools.
version: 0.0.2
repository: https://github.com/monkey-make-banana/flutter_chrome
homepage: https://monkey-make.com
topics: [cli, web, dart]

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  yaml: ^3.1.2
  image: ^4.1.3
  io: ^1.0.4
  args: ^2.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.3

executables:
  fc_setup: setup
  fc_build: build